=== doriveramirez/xquery_exam/bicicletas.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--DTD para un documento XML que contiene una lista de bicicletas de una fábrica del polígono industrial de Salinetas (Telde).-->

<!ELEMENT bicicletas (bicicleta+)>

<!ELEMENT bicicleta (idBicicleta,modelo,tipo,componentes)>

<!ELEMENT idBicicleta (#PCDATA)>

<!ELEMENT modelo (#PCDATA)>

<!ELEMENT tipo (#PCDATA)> <!-- Que puede ser PASEO, CARRERAS, INFANTIL, etc...   -->

<!ELEMENT componentes (componente+)>

<!ELEMENT componente (idComponente,nombreComponente,fabricacionPropia,costo)>

<!ELEMENT idComponente (#PCDATA)>

<!ELEMENT fabricacionPropia (#PCDATA)> <!-- Puede ser SI ó NO.   -->

<!ELEMENT nombreComponente (#PCDATA)>

<!ELEMENT costo (#PCDATA)> <!-- Cantidad de Euros de costo del componente   -->

=== doriveramirez/xquery_exam/bicicletas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bicicletas SYSTEM "bicicletas.dtd">
<bicicletas>
  <bicicleta>
    <idBicicleta>1</idBicicleta>
    <modelo>piccolina</modelo>
    <tipo>Paseo</tipo>
    <componentes>
      <componente>
        <idComponente>1</idComponente>
        <nombreComponente>Manillar</nombreComponente>
        <fabricacionPropia>No</fabricacionPropia>
        <costo>50</costo>
      </componente>
      <componente>
        <idComponente>2</idComponente>
        <nombreComponente>Ruedas</nombreComponente>
        <fabricacionPropia>Si</fabricacionPropia>
        <costo>90</costo>
      </componente>
    </componentes>
  </bicicleta>
  <bicicleta>
    <idBicicleta>2</idBicicleta>
    <modelo>Adios</modelo>
    <tipo>Carreras</tipo>
    <componentes>
      <componente>
        <idComponente>3</idComponente>
        <nombreComponente>Burro</nombreComponente>
        <fabricacionPropia>Si</fabricacionPropia>
        <costo>15</costo>
      </componente>
      <componente>
        <idComponente>2</idComponente>
        <nombreComponente>Ruedas</nombreComponente>
        <fabricacionPropia>No</fabricacionPropia>
        <costo>20</costo>
      </componente>
    </componentes>
  </bicicleta>
  <bicicleta>
    <idBicicleta>323</idBicicleta>
    <modelo>buenas</modelo>
    <tipo>Carreras</tipo>
    <componentes>
      <componente>
        <idComponente>3</idComponente>
        <nombreComponente>Burro</nombreComponente>
        <fabricacionPropia>Si</fabricacionPropia>
        <costo>15</costo>
      </componente>
      <componente>
        <idComponente>2</idComponente>
        <nombreComponente>Ruedas</nombreComponente>
        <fabricacionPropia>No</fabricacionPropia>
        <costo>30</costo>
      </componente>
    </componentes>
  </bicicleta>
</bicicletas>
